### ISSUE TITLE
How to call identify in MixpanelPeopleContext

### ISSUE THREAD

**Issue by divyenduz** [telegraf/telegraf-mixpanel#1]
The [current implementation](https://github.com/telegraf/telegraf-mixpanel/blob/develop/lib/mixpanel.js#L42) exposes various functions on the `people` object but does not allow identifying a user using the [identify method](https://developer.mixpanel.com/docs/javascript#section-managing-user-identity). 

This is also not documented yet. Is there already a way to do this?

**Comment by divyenduz** [comment]
I think that the [`setAsync` function](https://github.com/telegraf/telegraf-mixpanel/blob/develop/lib/mixpanel.js#L64) doesn't exist anymore and maybe this should be configurable anyways.

**Comment by divyenduz** [comment]
I tried `ctx.mixpanel.client.identify` but that does not work as well, maybe because it is on a very old version of [mixpanel](https://github.com/mixpanel/mixpanel-node/blob/master/package.json).

**Comment by LetItCode** [comment]
https://github.com/mixpanel/mixpanel-node/issues/13

**Comment by LetItCode** [comment]
> I tried `ctx.mixpanel.client.identify` but that does not work as well, maybe because it is on a very old version of [mixpanel](https://github.com/mixpanel/mixpanel-node/blob/master/package.json).

https://github.com/mixpanel/mixpanel-node/issues/13
